//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AandroidConversion
    {
        public int id { get; set; }
        public string sequence { get; set; }
        public string stage { get; set; }
        public string node { get; set; }
        public string value { get; set; }
    }
}
